Algoritmo "Divisão Números"
//  
//  

Var
// Seção de Declarações das variáveis 
   num1, num2, result: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite dois números o programa vai dividir o primeiro pelo segundo e mostrar o resultado.")
   escreval("")
   escreva("Digite o primeiro número: ")
   leia(num1)
   escreva("Digite o segundo número: ")
   leia(num2)
   result <- num1 / num2
   escreval("")
   escreval(num1, " / ", num2, " = ", result)

Fimalgoritmo