Algoritmo "Dobro Número"
//  
//  
Var
// Seção de Declarações das variáveis 
   num, dobro: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite um número, o programa exibira o seu dobro.")
   escreval("")
   escreva("Digite o seu número: ")
   leia(num)
   dobro <- num * 2
   escreval("")
   escreval("O dobro de ", num, " é ", dobro, ".")

Fimalgoritmo