Algoritmo "Raiz Quadrada do Número"
//  
//  
Var
// Seção de Declarações das variáveis 
   num, raiz: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite um número, o programa exibira a sua raiz quadrada.")
   escreval("")
   escreva("Digite o seu número: ")
   leia(num)
   raiz <- raizq(num)
   escreval("")
   escreval("A raiz quadrada de ",num, " é ", raiz, ".")

Fimalgoritmo