Algoritmo "Metade Número"
//  
//  

Var
// Seção de Declarações das variáveis 
   num, metade: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite um número, o programa exibira a sua metade.")
   escreval("")
   escreva("Digite o seu número: ")
   leia(num)
   metade <- num / 2
   escreval("")
   escreval("A metade de ", num, " é ", metade, ".")

Fimalgoritmo