Algoritmo "Numeros iguais"
//  
//  
// 
//  
Var
// Seção de Declarações das variáveis 
   num1, num2: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Escreva dois números inteiros, o programa exibir se os númeors são iguais.")
   escreva("Digite o primeiro número: ")
   leia(num1)
   escreval("")
   escreva("Digite o segundo número: ")
   leia(num2)
   escreval("")
   se(num1=num2) entao
                escreval("Os números são iguais.")
   senao
                escreval("Os números não são iguais.")
   fimse

Fimalgoritmo