Algoritmo "Primeiro Número Menor"
//  
//  
// 
//  
Var
// Seção de Declarações das variáveis 
   num1, num2: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Escreva dois números inteiros, o programa exibir se o primeiro número é menor que o segundo número.")
   escreva("Digite o primeiro número: ")
   leia(num1)
   escreval("")
   escreva("Digite o segundo número: ")
   leia(num2)
   escreval("")
   se(num1<num2) entao
                escreval("O primeiro número é menor que o segundo.")
   senao
                escreval("O primeior número não é menor que o segundo")
   fimse

Fimalgoritmo