Algoritmo "Subtração Números"
//  
//  

Var
// Seção de Declarações das variáveis 
   num1, num2, result: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite dois números o programa vai subtrair o segundo pelo primeiro e mostrar o resultado.")
   escreval("")
   escreva("Digite o primeiro número: ")
   leia(num1)
   escreva("Digite o segundo número: ")
   leia(num2)
   result <- num2 - num1
   escreval("")
   escreval(num2, " - ", num1, " = ", result)

Fimalgoritmo