Algoritmo "Quadrado do Número"
//  
//  
Var
// Seção de Declarações das variáveis 
   num, quadrado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite um número, o programa exibira o seu quadrado.")
   escreval("")
   escreva("Digite o seu número: ")
   leia(num)
   quadrado <- num ^ 2
   escreval("")
   escreval(num, " ao quadrado é ", quadrado, ".")

Fimalgoritmo